### ISSUE TITLE
Change index page to index-design-creative.html template

### ISSUE THREAD

**Issue by k3nn3dyG** [brightplum/brightplumv2#4]
This template can be found in the theme_forest folder under ave.html

**Comment by designking06** [comment]
The name seems a bit long, and we may end up using modules from other layouts in the theme folder. 
Could we just insert a comment inside index.html saying that we are using the design creative template?

**Comment by designking06** [comment]
If you feel we should stick with the same you changed to, do you plan on changing the permalink inside the code? 
Ex:
Layout: default
#title 
Permalink: index.html

**Comment by k3nn3dyG** [comment]
completed
